/**
 * Generate THREAT-COVERAGE.md: a measured catalog of what RepoCanary detects.
 *
 * This is not a hand-maintained list that drifts from the code. Every row is
 * produced by running the real engine over the threat corpus in
 * benchmark-samples.js and recording exactly which rules fire and what verdict
 * results. If a rule is renamed or a sample stops matching, this file changes
 * on the next run, so the document cannot lie about coverage.
 *
 *   node scripts/coverage.js            write THREAT-COVERAGE.md
 *   node scripts/coverage.js --check    fail if the file is out of date (CI)
 *
 * The engine never runs, clones, or installs a target. Samples are scanned
 * in memory as text, the same path a real scan uses.
 */

import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { MALICIOUS, EVASIONS, BENIGN } from "./benchmark-samples.js";
import { byCategory, detection, firedRules, scanSample } from "./grade.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "THREAT-COVERAGE.md");
// Machine-readable twin of the catalog, imported by the site's /coverage page
// so the branded page renders the same measured data and cannot drift.
const OUT_JSON = join(ROOT, "web", "lib", "coverage-data.json");

async function scan(sample) {
  const result = await scanSample(sample);
  return { verdict: result.verdict, rules: firedRules(result.findings) };
}

const VERDICT_MARK = { red: "RED", yellow: "flag", green: "green" };
const ruleLabel = (r) => `${r.id} (${r.sev[0]})`;

function table(rows) {
  const lines = ["| Technique | What it is | Verdict | Rules that fired |", "| --- | --- | --- | --- |"];
  for (const r of rows) {
    const cell = r.rules.length ? r.rules.map((x) => `\`${ruleLabel(x)}\``).join(", ") : "(none)";
    lines.push(`| \`${r.name}\` | ${r.note} | ${VERDICT_MARK[r.verdict] ?? r.verdict} | ${cell} |`);
  }
  return lines.join("\n");
}

const titleCase = (s) => `${s[0].toUpperCase()}${s.slice(1)}`;
const rowData = (r) => ({ name: r.name, note: r.note, verdict: r.verdict, rules: r.rules });

/** The catalog and its JSON twin, rendered from the corpus. */
export async function renderCoverage() {
  const scanned = [];
  for (const s of MALICIOUS) scanned.push({ ...s, ...(await scan(s)) });
  const evasions = [];
  for (const s of EVASIONS) evasions.push({ ...s, ...(await scan(s)) });

  const grouped = byCategory(scanned);
  const categories = [...grouped.keys()];

  const distinctRules = new Set();
  for (const s of scanned) for (const r of s.rules) distinctRules.add(r.id);

  const detectionPct = detection(scanned).pct;

  const out = [];
  out.push("# Threat coverage");
  out.push("");
  out.push("<!-- Generated by scripts/coverage.js. Do not edit by hand; run `node scripts/coverage.js`. -->");
  out.push("");
  out.push(
    "This is the catalog of fake-interview and supply-chain techniques RepoCanary " +
      "detects, and it is measured, not asserted. Every row below is produced by running " +
      "the real detection engine over a synthetic corpus of the techniques these campaigns " +
      "use (Contagious Interview, BeaverTail, InvisibleFerret, OtterCookie, and the wider " +
      "npm and PyPI supply-chain playbook), and recording exactly which rules fire and what " +
      "verdict results. Nothing here is run, cloned, or installed: each sample is scanned as " +
      "text, the same path a real scan uses.",
  );
  out.push("");
  out.push("Regenerate with `node scripts/coverage.js`. CI runs `node scripts/coverage.js --check` so this file cannot drift from the rules.");
  out.push("");
  out.push("## At a glance");
  out.push("");
  out.push(`- **${scanned.length}** distinct malicious techniques in the corpus, across **${categories.length}** categories`);
  out.push(`- **${detectionPct}%** caught (each flagged for review or convicted outright)`);
  out.push(`- **${distinctRules.size}** distinct detection rules exercised by the corpus`);
  out.push(`- **${evasions.length}** evasion cases the tool honestly does not catch, held as runnable samples (listed at the end, not hidden). THREAT-MODEL.md argues the wider set of limits.`);
  out.push("");
  out.push("Verdict column: **RED** = do not run, a high-confidence signal fired; **flag** = flagged for human review; **green** = nothing known matched.");
  out.push("");

  for (const cat of categories) {
    out.push(`## ${titleCase(cat)}`);
    out.push("");
    out.push(table(grouped.get(cat)));
    out.push("");
  }

  out.push("## Documented evasions (known blind spots)");
  out.push("");
  out.push(
    "A tool that claims to catch everything is lying. These are techniques the static " +
      "engine does not reliably catch, kept in the corpus so the limit is measured and " +
      "visible rather than quietly forgotten. Green never means safe; it means nothing " +
      "known matched.",
  );
  out.push("");
  out.push(table(evasions));
  out.push("");

  const body = out.join("\n") + "\n";

  // Structured twin for the site's /coverage page. Deterministic (no
  // timestamp) so the freshness check is stable.
  const data = {
    stats: {
      techniques: scanned.length,
      categories: categories.length,
      rules: distinctRules.size,
      detectionPct,
      // No false-positive count: this script scans the malicious corpus only.
      // scripts/benchmark.js measures that against the real repositories.
      benignRepos: BENIGN.length,
      evasions: evasions.length,
    },
    campaigns: ["Contagious Interview", "BeaverTail", "InvisibleFerret", "OtterCookie"],
    categories: categories.map((cat) => ({ name: titleCase(cat), rows: grouped.get(cat).map(rowData) })),
    evasions: evasions.map(rowData),
  };
  const json = JSON.stringify(data, null, 2) + "\n";
  return { body, json, techniques: scanned.length, rules: distinctRules.size, detectionPct };
}

async function main() {
  const check = process.argv.includes("--check");
  const { body, json, techniques, rules, detectionPct } = await renderCoverage();

  if (check) {
    const stale = [];
    for (const [path, want] of [
      [OUT, body],
      [OUT_JSON, json],
    ]) {
      let current = "";
      try {
        current = readFileSync(path, "utf8");
      } catch {
        // missing file: treated as out of date below
      }
      if (current !== want) stale.push(path);
    }
    if (stale.length) {
      console.error(`Out of date (${stale.join(", ")}). Run: node scripts/coverage.js`);
      process.exitCode = 1;
      return;
    }
    console.log("Threat-coverage catalog and data are up to date.");
    return;
  }

  writeFileSync(OUT, body);
  writeFileSync(OUT_JSON, json);
  console.log(`Wrote ${OUT} and ${OUT_JSON}: ${techniques} techniques, ${rules} rules, ${detectionPct}% caught.`);
}

// Only run when invoked as a program, not when imported by the tests.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) main();
